version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: pedefree-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: pedefree
      POSTGRES_PASSWORD: pedefree123
      POSTGRES_DB: pedefree
    ports:
      - "5432:5432"
    volumes:
      - pedefree_pgdata:/var/lib/postgresql/data

volumes:
  pedefree_pgdata:
